name: Discord Webhook
on:
  push:
    branches:
      - main

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Webhook
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" -X POST -d '{"content": "This is a test message!"}' $WEBHOOK_URL
