# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Prominent
author: Evvy
baseurl: "/recruitment" # the subpath of your site, e.g. /blog
url: "https://evvy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/media/promi.png"
# exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

##################
# Build settings #
##################

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.5.4
search_enabled: false
# Aux links for the upper right navigation
aux_links:
  Prominent on Discord:
    - "https://discord.gg/fyMSxzubHa"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
# Footer content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2023 Evvy. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
#Callouts - Pre-set
callouts:
  warning:
    title: Warning
    color: red

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
